# Generated by Django 3.0.2 on 2020-11-28 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orientacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orientacao',
            name='user',
        ),
        migrations.AddField(
            model_name='orientacao',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
