# Generated by Django 3.0.2 on 2021-02-01 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orientacao', '0002_auto_20201128_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientacao',
            name='orientandos',
            field=models.ManyToManyField(blank=True, related_name='orientandos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='orientacao',
            name='user',
        ),
        migrations.AddField(
            model_name='orientacao',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
    ]
